### ISSUE TITLE
[ISSUE ACCEPTED] Getting InvalidResponseException

### ISSUE THREAD

**Issue by Stoneunit** [Spegeli/PokemoGoBot-GottaCatchEmAll#86]
Unhandled exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\Users\User\Desktop\pokemon go\Pokemon-Go-Rocket-API-master\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__32.MoveNext() in C:\Users\Toby\Desktop\pokemon go\Pokemon-Go-Rocket-API-master\PokemonGo.RocketAPI\Client.cs:line 241
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Utils.Statistics.<UpdateConsoleTitle>d__21.MoveNext() in C:\Users\Toby\Desktop\pokemon go\Pokemon-Go-Rocket-API-master\PokemonGo.RocketAPI.Logic\Utils\Statistics.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Press any key to continue . . .

**Comment by Stoneunit** [comment]
Happens about 2-3 hours of the bot running and closes after "Pressing any key"

**Comment by GottEnton** [comment]
i got the same error after botting for like 5 hours on both of my accounts ( 1google / 1 Ptc ) 

[11:27:03] (TRANSFER) Spearow (CP 10 | 57,13 % perfect) | (Best: 553 CP | 90,02
% perfect)
[11:27:04] (NAVIGATION) We are within 40 meters of the target. Speeding down to
10 km/h to not pass the target.
[11:27:08] (POKESTOP) XP: 50, Gems: 0, Eggs: 0, Items: 1 x ItemRazzBerry, 1 x It
emPokeBall, 1 x ItemRevive
[11:27:09] (POKESTOP) Name: San Remo Tower in 97,94 m distance
[11:27:09] (NAVIGATION) Distance to target location: 97,94 meters. Will take 4,7
 seconds!
[11:27:12] (NAVIGATION) We are within 40 meters of the target. Speeding down to
10 km/h to not pass the target.
[11:27:16] (POKESTOP) XP: 50, Gems: 0, Eggs: 0, Items: 1 x ItemGreatBall, 2 x It
emPokeBall
Unhandled exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Ei
ne Ausnahme vom Typ "PokemonGo.RocketAPI.Exceptions.InvalidResponseException" wu
rde ausgelöst.
   bei PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__
1`2.MoveNext() in C:\Users\Fickfresse\Downloads\pokemon\SpegeliBot\Ptc\Pokemon-G
o-Rocket-API-master(2)\Pokemon-Go-Rocket-API-master\PokemonGo.RocketAPI\Extensio
ns\HttpClientExtensions.cs:Zeile 40.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausge
löst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
tification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei PokemonGo.RocketAPI.Client.<GetInventory>d__31.MoveNext() in C:\Users\Fic
kfresse\Downloads\pokemon\SpegeliBot\Ptc\Pokemon-Go-Rocket-API-master(2)\Pokemon
-Go-Rocket-API-master\PokemonGo.RocketAPI\Client.cs:Zeile 230.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausge
löst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
tification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei PokemonGo.RocketAPI.Logic.Utils.Statistics.<UpdateConsoleTitle>d__21.Move
Next() in C:\Users\Fickfresse\Downloads\pokemon\SpegeliBot\Ptc\Pokemon-Go-Rocket
-API-master(2)\Pokemon-Go-Rocket-API-master\PokemonGo.RocketAPI.Logic\Utils\Stat
istics.cs:Zeile 92.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausge
löst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b_
_6_1(Object state)
   bei System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object st
ate)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionC
ontext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext,
ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWo
rkItem.ExecuteWorkItem()
   bei System.Threading.ThreadPoolWorkQueue.Dispatch()
   bei System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Drücken Sie eine beliebige Taste . . .

**Comment by Spegeli** [comment]
Yes this happens randomly but currently i dont know why.
I'm searching for the issue ;-)

**Comment by Spegeli** [comment]
Ok it seems i found the issue.
The Statistic was using the direct query for the GetInventory() instead using the new getCachedInventory logic which includes are error catch function.

Doing now some tests and when everything works fine, i will upload tomorrow the new version.

**Comment by umbralogix** [comment]
Still getting this even on the latest update 

[14:04:01] (ERROR) InvalidResponseException from HttpClientExtensions.cs
[14:04:01] (ERROR) InvalidResponseException from HttpClientExtensions.cs
[14:04:01] Specified argument was out of the range of valid values.
Parameter name: index from Google.Protobuf
[14:04:02] (ERROR) InvalidResponseException from getCachedInventory

**Comment by vietxflash** [comment]
Getting InvalidResponseException from getCachedInventory

**Comment by umbralogix** [comment]
Also:

```
[14:08:35] (ERROR) InvalidResponseException from HttpClientExtensions.cs
[14:08:35] Specified argument was out of the range of valid values.
Parameter name: index from Google.Protobuf
[14:08:35] (ERROR) InvalidResponseException from getCachedInventory
Unhandled exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
   at PokemonGo.RocketAPI.Logic.Inventory.<getCachedInventory>d__18.MoveNext() in C:\Users\umbra\Desktop\PokemoGoBot-GottaCatchEmAll-master\PokemoGoBot-GottaCatchEmAll-master\PokemonGo.RocketAPI.Logic\Inventory.cs:line 278
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Utils.Statistics.<UpdateConsoleTitle>d__21.MoveNext() in C:\Users\umbra\Desktop\PokemoGoBot-GottaCatchEmAll-master\PokemoGoBot-GottaCatchEmAll-master\PokemonGo.RocketAPI.Logic\Utils\Statistics.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Press any key to continue . . .
```
